version: "2"
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 30
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 5
  return-statements:
    config:
      threshold: 5
engines:
  eslint:
    enabled: true
    channel: "eslint-3"
  csslint:
    enabled: true
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**/*
exclude_paths:
- test/**/*
