version: 2
jobs:
  build:
    working_directory: ~/chunky
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: npm run coverage
      - run:
          name: Generate code climate
          command: npm run codeclimate
      - store_artifacts:
          path: coverage
          prefix: coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
