version: 2
jobs:
  build:
    working_directory: ~/chunky
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: npm run coverage
      - run:
          name: Generate code climate
          command: npm run codeclimate
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
